ENCODE-DCC/snovault

- src/snovault/embed.py
- src/snovault/resources.py
- src/snovault/util.py
With this change, indexing an ENCODED demo instance took 6 hours (compared to 7-8 which Ben said is typical)
> Replace copy.deepcopy with something faster

- src/snovault/tests/serverfixtures.py
- src/snowflakes/tests/__init__.py
Same PR as #25 except the branch is now in this repo.
The proposed code modifies the `wsgi_server_host_port` fixture in `serverfixtures.py` so that if two specific arguments are passed to it, it will initiate the WSGI test server in the specified port range. This is useful if your browser tests need to be run on specific ports (eg ClinGen needs to be run on specific ports for testing Auth0 authentication). If the arguments are missing the fixture will default to `webtest.http`'s `get_free_port`method as before.
The extra code was derived from `webtest.http`'s `get_free_port` method, with modifications to make it loop through the specified port range until it finds a free port. If a free port is not found within the range, it will raise an exception.
Testing:
1. Browser tests should run on …
> Add ability to specify ports for wsgi test server

- CHANGES.rst
- README.rst
- setup.py
- src/snovault/elasticsearch/create_mapping.py
- src/snowflakes/schemas/page.json
This is needed so I can fix encoded issue 4911 (I need a way to disable indexing of the page type's layout.rows field)
@hitz when you merge this can you add the missing entries to the changelog for the other changes that have been merged to master since 0.23 was released?
> Add a way to explicitly override a field's mapping

- src/snovault/elasticsearch/mpindexer.py
This just sets maxchildtasks=4 in the multiprocessing Pool used by the indexer.
It has been tested as part of encoded (redmine) ticket 5079: http://redmine.encodedcc.org/issues/5079
> 21 maxtasks

- src/snovault/batchupgrade.py
- src/snovault/elasticsearch/mpindexer.py
- src/snovault/tests/test_post_put_patch.py
- src/snovault/tests/testing_views.py
- src/snowflakes/__init__.py
- src/snowflakes/audit/item.py
- src/snowflakes/authorization.py
- src/snowflakes/schema_formats.py
- src/snowflakes/schemas/award.json
- src/snowflakes/schemas/mixins.json
- src/snowflakes/schemas/snowball.json
- src/snowflakes/schemas/snowfort.json
- src/snowflakes/schemas/snowset.json
- src/snowflakes/schemas/user.json
- src/snowflakes/tests/data/inserts/award.json
- src/snowflakes/tests/datafixtures.py
- src/snowflakes/tests/test_audit_item.py
- src/snowflakes/tests/test_batch_upgrade.py
- src/snowflakes/tests/test_server_defaults.py
- src/snowflakes/tests/test_upgrade_award.py
- src/snowflakes/upgrade/award.py
- src/snowflakes/upgrade/snowset.py
The actually fix is in batchupgrade.py, it was just barfing because error.path was unrolling with integers representing list indices.   This bug was masked because it's only triggered by validation errors in elements of lists (in this case, alternate_accessions).
The code that tests this change is here: src/snowflakes/tests/test_batch_upgrade.py
The rest of the code additions are just adding a bunch of lost testing functionality for upgrades back from encoded to snovault/snowflakes.  This includes sample audit code in src/snowflakes/audits as well as adding back the schema_formats.py which was broken in encoded in the previous release.
The deleted test in test_post_put_patch was discovered by Bek to be throwing stuff to standard error.   In a bunch of exploratory code I determined that …
> ENCD-3358 5161 batchupgrade errors

- .travis.yml
- src/snovault/authentication.py
- src/snovault/crud_views.py
- src/snovault/resource_views.py
- src/snovault/schema_utils.py
- src/snovault/schema_views.py
- src/snowflakes/tests/features/customsteps.py
- src/snowflakes/tests/features/forms.feature
- src/snowflakes/tests/features/test_submitter_user.py
* Added a new `form` frame which includes the object's `@type`
so that the frontend can determine which schema to use for form building.
* Added a `_subtypes` mapping to the `/profiles/` view so that the
frontend can provide a menu of options for what subtype of child to add.
* When putting an object that incldues an update to an existing child object,
look up the existing object's `@type` and use that schema for validation,
rather than the abstract type schema.
* When putting an object that includes a new child object,
if the linkFrom property for that child uses an abstract type,
the child must specify a `@type` so that the backend knows what
schema to use for validation and which collection to add it to.
* Fix `update_children` to set the link value correctly when it is an
array of …
> Various changes to handle adding/editing child objects of abstract types (ENCD-2164)

- src/snovault/schema_views.py
- src/snovault/util.py
The schema views are supposed to set `readonly: True` for a property if it uses a permission that the current user does not have. This fixes that to work at any level of a schema, not just the top level of properties.
> ENCD-3583 fix field permissions for nested schemas

- src/snovault/elasticsearch/indexer.py
Code commented out (as other 2-pass code is).  This stale audit code was not interfering with original indexing but was interfering when audits were supposed to change.
> Stale audit code interfered with 1-pass indexing.

- CHANGES.rst
- README.rst
- buildout.cfg
Here is a fix for the "Couldn't find a distribution" errors that doesn't require messing with buildout and setuptools versions.
> Specify https index to fix buildout, update changelog

- CHANGES.rst
- src/snovault/typeinfo.py
Here is a follow-up to my previous change for ENCD-3669, to fix an issue that was discovered during QA (see discussion on the ticket). The edit view of an object should not include properties that cannot be submitted.
Unlike my last snovault change, there is no corresponding change in encoded which depends on this. So this just needs to be merged, released, and then encoded updated to the new release.
> ENCD-3669(update) Omit notSubmittable rev links in edit view

- src/snowflakes/static/components/globals.js
Hello!
The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).
Cheers :-)
> SNO-19 Update DOI preferred resolver url

- src/snovault/auditor.py
- src/snovault/elasticsearch/esstorage.py
This makes 2 changes to help performance just after an item is edited:
1. If an item is fetched from elasticsearch but turns out to have been invalidated, then set the request's datastore to `database` so that fetches of other items will go directly to the database (basically, assume that they are likely to have been invalidated too).
2. Don't embed audits in items unless they were fetched from elasticsearch. This way we only incur the overhead of calculating audits while indexing.
> SNO-29 Limit audits on form update

- src/snovault/schema_views.py
PRing so Laurence can review to see if I’ve gone mad. 😜
The main question is whether adding this new /profiles-map/ route is a good idea. When viewing a schema now, we can have `<a>` links to other schemas via the linkTo and linkFrom properties. But those only contain the other schema’s `@type` that doesn’t have a necessarily obvious mapping to a schema path. I could have done a GET on /profiles/ but that returns 1.2MB JSON. So I made this new path that has the same dict keys as /profiles/ but the values are just the schema path strings instead of the entire string object, and right now that returns in 5.9KB JSON.
```
{
"AccessKey": "/profiles/access_key_admin.json",
"AnalysisStep": "/profiles/analysis_step.json",
"AnalysisStepRun": "/profiles/analysis_step_run.json", …
```
> SNO-26 Add schemas map view to profiles

- src/snovault/schema_utils.py
- src/snovault/tests/test_schema_utils.py
This addresses https://encodedcc.atlassian.net/browse/SNO-25 where if the same linked object was specified in two different forms (i.e. uuid and @id), uniqueItems would not catch it.
I'm fixing this by overriding the `uniqueItems` validator to look at the validated, serialized values returned from the `items` subschema (in the case discussed in the ticket, those are normalized to uuids by the `linkTo` validator) rather than the raw values from the request. This will only be in place if the `items` validator is processed before the `uniqueItems` validator; fortunately the `jsonschema` library explicitly sets up `items` to run early.
> SNO-25 Make uniqueItems to check the serialized values

- src/snovault/elasticsearch/create_mapping.py
- src/snovault/elasticsearch/esstorage.py
- src/snovault/elasticsearch/interfaces.py
- src/snowflakes/search.py
This avoids searching unrelated indexes such as the vis cache and regions. Seems to make getting a single object 40-100% faster on my laptop with test data.
> SNO-28 limit ES storage to indices created for snovault resources

- src/snovault/connection.py
- src/snovault/elasticsearch/esstorage.py
- src/snovault/resources.py
- src/snovault/storage.py
This will hopefully improve performance for fetching single objects at their canonical URI.
This is based on the changes from #93 so you can check the cumulative performance improvement in a demo -- start one from the SNO-33-one-index branch of `encoded`, which uses this snovault branch. Look at the more recent commit to see just the changes related to SNO-33.
Note that this involves a small change to the interface for storages -- the `get_by_unique_key` method must now take an optional `index` parameter.
> SNO-33 Specify index for get_by_unique_key from collection

- src/snovault/attachment.py
- src/snovault/tests/test_attachment.py
This allows for protected documents to be downloaded regardless of auth parameter passed into the request.
> SNO-34-attachment-download

- src/snovault/nginx-dev.conf
This removes authorization and content-type headers from nginx-dev config.
> SNO-34-nginx-dev-proxy-headers

- src/snovault/elasticsearch/indexer.py
Code that uses get_related_uuids is expecting a set/list, not a generator.
> SNO-38-fix-return-mismatch

- setup.py
- src/snovault/storage.py
- src/snovault/tests/test_storage.py
- versions.cfg
This tries to recreate the boto functionality in S3BlobStorage with boto3. Several boto methods don't have equivalent methods in boto3. The storage parameters `read_profile_name=None, store_profile_name=None` never seemed to be used so removed. The `store_conn` and `read_conn` abstractions likewise didn't seem useful to recreate.
> SNO-40-upgrade-boto3

- src/snovault/tests/test_storage.py
This fixes subtle mock bug undetected in Python 3.4, but apparent in 3.5 and 3.6. Uses an explicit check of call count now instead of the assert_called_once method.
> SNO-42-fix-assert-called-once

- src/snowflakes/search.py
Ben or I could not find where this search_type arg was ever used.  It can't be added as a query parameter because it wasn't set up properly.  Is was in the way for search refactor epic so we're removing it.
ENCD-4154 for similar snowflakes updates
> SNO-46 Remove unused search type arg

- src/snovault/connection.py
Increasing embed cache size for loading large objects (like publication-data) with a lot of files.
> SNO-45-increase-embed-cache

- src/snovault/elasticsearch/indexer.py
- src/snovault/elasticsearch/indexer_state.py
- src/snovault/elasticsearch/mpindexer.py
Goes with ENCD-4209 PR.  Someone could add a reminder to revert the short indexer commit to their approval.  I would but I can't review my own pr.
There are three indexer states flagged in the PR.  
1.  The initial indexing state.  First index or indexing has been reset.
2. Reindex = all.  This end point resets the indexer.  This case and reindex and init index flags as true.
3. Reindex not all.  This end pint creates a list of uuids to reindex and does not reset the indexer.
After this PR I will submit a indexing logger PR, SNO-47.  It will dump indexer data to a json file when one or both of these variables are true.
> SNO-53+59 Add index flags to indexers+Log name

- src/snovault/schema_views.py
Add a new endpoint, `/profiles-titles/`, that returns an object keyed by every @type in the system, and the corresponding `title` property from the schema, if available. This snovault branch is required for the ENCD-4033-search-header-profile branch.
> SNO-66 Add new endpoint to map schema @types to schema titles

- src/snovault/attachment.py
- First, I put md5sum check before image verification. I believe this shouldn't change anything
- Second, all changes should be restricted to only jpeg and tiff files with valid orientation between 2 to 8 (both included). Please confirm that.
- For jpeg and tiff being rotated, the md5sum, data itself, width and height should be up to date. Especially for the data, I hope it's the correct bytes.
> SNO-83 Rotate img attachment for EXIF

- src/snovault/elasticsearch/create_mapping.py
- src/snovault/helpers/helper.py
- src/snovault/viewconfigs/searchview.py
Improve free-text queries by adding english and word-delimiter analyzers to `_all` and removing ngrams analyzer. Set the default analyzer to use this chain as well. Only search over `_all` field.
> SNO-108-improve-search-new
